// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8MujYLyTffnraEH9W2ZDzqsh0MrxI228',
    appId: '1:556879010522:web:51ac5a5f85523f7e4a23e3',
    messagingSenderId: '556879010522',
    projectId: 'chatapp-feaa9',
    authDomain: 'chatapp-feaa9.firebaseapp.com',
    databaseURL: 'https://chatapp-feaa9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-feaa9.firebasestorage.app',
    measurementId: 'G-0ZQN43P27B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUIs0xIiGayFYPbhA7iKj1r8fbYETqhio',
    appId: '1:556879010522:android:9114e913e18804f14a23e3',
    messagingSenderId: '556879010522',
    projectId: 'chatapp-feaa9',
    databaseURL: 'https://chatapp-feaa9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-feaa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyAu4iN8a-OM-glcmFHx2uAh2Xsq5JDok',
    appId: '1:556879010522:ios:c598f148d6218dc94a23e3',
    messagingSenderId: '556879010522',
    projectId: 'chatapp-feaa9',
    databaseURL: 'https://chatapp-feaa9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-feaa9.firebasestorage.app',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyAu4iN8a-OM-glcmFHx2uAh2Xsq5JDok',
    appId: '1:556879010522:ios:c598f148d6218dc94a23e3',
    messagingSenderId: '556879010522',
    projectId: 'chatapp-feaa9',
    databaseURL: 'https://chatapp-feaa9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-feaa9.firebasestorage.app',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8MujYLyTffnraEH9W2ZDzqsh0MrxI228',
    appId: '1:556879010522:web:a56b9d2c9d275a8d4a23e3',
    messagingSenderId: '556879010522',
    projectId: 'chatapp-feaa9',
    authDomain: 'chatapp-feaa9.firebaseapp.com',
    databaseURL: 'https://chatapp-feaa9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-feaa9.firebasestorage.app',
    measurementId: 'G-GPW9N4YNWG',
  );

}